apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels: 
    project: expense
    tier: db
    app: mysql
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: expense
      tier: db
      app: mysql
  template:
    metadata:
      labels:
        project: expense
        tier: db
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mlndockerhub/mysql:v1

--- 
apiVersion: v1 
kind: Service
metadata: 
  name: mysql
  namespace: expense
spec: 
  selector: 
    project: expense
    tier: db
    app: mysql
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
